### ISSUE TITLE
Umiejętność podróżowania

### ISSUE THREAD

**Issue by telemetrik** [zyczynski/obiektowy#7]
1. Dodaj na klasie User ustawianie preferowanej formy transportu
2. Jak skończysz 1

**Comment by zyczynski** [comment]
To powinno być w konstruktorze?

**Comment by telemetrik** [comment]
Masz dwie opcje - albo konstruktor albo setter (czyli normalna metoda wewnątrz klasy, która ustawia (settuje) jakąś własność). Żeby dokonać wyboru musisz odpowiedzieć sobie na pytanie - czy preferowana forma transportu jest własnością NIEZBĘDNĄ / taką z którą rodzi się użytkownik i nie może bez niej istnieć czy nie. Jeśli tak - konstruktor, jeśli nie - setter.

**Comment by zyczynski** [comment]
Pozmieniałem wszystkie nazwy na angielskie i postaram się tego trzymać ;)
No szczerze mówiąc tak średnio rozumiem, ale to chyba przyjdzie samo. Bez tego interfejsu też by to dało radę zrobić cnie?
Co dalej?

**Comment by telemetrik** [comment]
A czego nie rozumiesz?

**Comment by telemetrik** [comment]
Objaśnię :)

**Comment by zyczynski** [comment]
W sumie to nie wiem, albo nie potrafię wyartykułować  ;) Nie czuje tego jakoś, chyba chodzi o samą koncepcję tego interfejsu.

**Comment by telemetrik** [comment]
Interfejs to coś co kategoryzuje Ci rzeczy. W życiu codziennym `Zwierze` moze byc przykładem interfejsu a `Kot` i `Pies` mogą go implementować. I niech to będzie Twoje następne zadanie (po angielsku). :) Dodaj możliwość dodawania zwierzaka do osoby na podstawie interfejsu (bo możesz mieć albo psa albo kota i nie chcemy ograniczać się do jednego albo tworzyć dwóch setterów `dodajPsa()` i `dodajKota()`.
